# Generated by Django 2.2.16 on 2022-04-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='biography',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='role',
        ),
    ]
